resolver: lts-11.6
allow-newer: true
packages:
- '.'
extra-deps:
- rio-0.1.1.0
- data-interval-1.3.0
- extended-reals-0.2.3.0
- distributed-process-async-0.2.4.1
- distributed-process-client-server-0.2.3
- distributed-process-extras-0.3.2
- megaparsec-6.3.0

- git: git@github.com:agentm/project-m36.git
  commit: 9d2c248bb497e6298625c0793b38ffe86351ec6d